# file auto-generated by <nixos-servers>/scripts/mullvad-mkservers on 2025-11-07T01:47:39+01:00
# from https://api.mullvad.net/www/relays/all/
{
  "ch-zrh-wg-001" = {
    publicKey = "/iivwlyqWqxQ0BVWmJRhcXIFdJeo0WbHQ/hZwuXaN3g=";
    ipv4.addr = "193.32.127.66";
    ipv6.addr = "2a03:1b20:a:f011::f001";
  };
  "ch-zrh-wg-002" = {
    publicKey = "qcvI02LwBnTb7aFrOyZSWvg4kb7zNW9/+rS6alnWyFE=";
    ipv4.addr = "193.32.127.67";
    ipv6.addr = "2a03:1b20:a:f011::f101";
  };
  "ch-zrh-wg-003" = {
    publicKey = "5Ms10UxGjCSzwImTrvEjcygsWY8AfMIdYyRvgFuTqH8=";
    ipv4.addr = "193.32.127.68";
    ipv6.addr = "2a03:1b20:a:f011::f201";
  };
  "ch-zrh-wg-004" = {
    publicKey = "C3jAgPirUZG6sNYe4VuAgDEYunENUyG34X42y+SBngQ=";
    ipv4.addr = "193.32.127.69";
    ipv6.addr = "2a03:1b20:a:f011::f301";
  };
  "ch-zrh-wg-005" = {
    publicKey = "dV/aHhwG0fmp0XuvSvrdWjCtdyhPDDFiE/nuv/1xnRM=";
    ipv4.addr = "193.32.127.70";
    ipv6.addr = "2a03:1b20:a:f011::f401";
  };
  "ch-zrh-wg-006" = {
    publicKey = "wDjbvO94t0UI1RlimpEFFv7kJ6DngthvuRX6uBN0wAA=";
    ipv4.addr = "193.32.127.84";
    ipv6.addr = "2a03:1b20:a:f011::f601";
  };
  "de-ber-wg-001" = {
    publicKey = "0qSP0VxoIhEhRK+fAHVvmfRdjPs2DmmpOCNLFP/7cGw=";
    ipv4.addr = "193.32.248.66";
    ipv6.addr = "2a03:1b20:b:f011::a01f";
  };
  "de-ber-wg-002" = {
    publicKey = "8ov1Ws0ut3ixWDh9Chp7/WLVn9qC6/WVHtcBcuWBlgo=";
    ipv4.addr = "193.32.248.67";
    ipv6.addr = "2a03:1b20:b:f011::a02f";
  };
  "de-ber-wg-003" = {
    publicKey = "USrMatdHiCL5AKdVMpHuYgWuMiK/GHPwRB3Xx00FhU0=";
    ipv4.addr = "193.32.248.68";
    ipv6.addr = "2a03:1b20:b:f011::a03f";
  };
  "de-ber-wg-004" = {
    publicKey = "6PchzRRxzeeHdNLyn3Nz0gmN7pUyjoZMpKmKzJRL4GM=";
    ipv4.addr = "193.32.248.69";
    ipv6.addr = "2a03:1b20:b:f011::a04f";
  };
  "de-ber-wg-005" = {
    publicKey = "I4Y7e8LrtBC/7DLpUgRd5k+IZk+whOFVAZgbSivoiBI=";
    ipv4.addr = "193.32.248.70";
    ipv6.addr = "2a03:1b20:b:f011::a05f";
  };
  "de-ber-wg-006" = {
    publicKey = "eprzkkkSbXCANngQDo305DIAvkKAnZaN71IpTNaOoTk=";
    ipv4.addr = "193.32.248.71";
    ipv6.addr = "2a03:1b20:b:f011::a06f";
  };
  "de-ber-wg-007" = {
    publicKey = "/ejdxiEsmYbeXXCN6UzvzJ0U/mLuB6baIfQRYKYHWzU=";
    ipv4.addr = "193.32.248.75";
    ipv6.addr = "2a03:1b20:b:f011::f701";
  };
  "de-ber-wg-008" = {
    publicKey = "qwXs9gwhwqWgRtLjPiZ+zMphZJA3OStsn/aXcCAd5m0=";
    ipv4.addr = "193.32.248.74";
    ipv6.addr = "2a03:1b20:b:f011::f801";
  };
  "de-fra-wg-001" = {
    publicKey = "HQHCrq4J6bSpdW1fI5hR/bvcrYa6HgGgwaa5ZY749ik=";
    ipv4.addr = "185.213.155.73";
    ipv6.addr = "2a03:1b20:6:f011::f001";
  };
  "de-fra-wg-002" = {
    publicKey = "s1c/NsfnqnwQSxao70DY4Co69AFT9e0h88IFuMD5mjs=";
    ipv4.addr = "185.213.155.74";
    ipv6.addr = "2a03:1b20:6:f011::f101";
  };
  "de-fra-wg-003" = {
    publicKey = "vVQKs2TeTbdAvl3sH16UWLSESncXAj0oBaNuFIUkLVk=";
    ipv4.addr = "185.209.196.73";
    ipv6.addr = "2a03:1b20:6:f011::f201";
  };
  "de-fra-wg-004" = {
    publicKey = "tzYLWgBdwrbbBCXYHRSoYIho4dHtrm+8bdONU1I8xzc=";
    ipv4.addr = "185.209.196.74";
    ipv6.addr = "2a03:1b20:6:f011::f301";
  };
  "de-fra-wg-005" = {
    publicKey = "tpobOO6t18CzHjOg0S3RlZJMxd2tz4+BnRYS7NrjTnM=";
    ipv4.addr = "185.209.196.75";
    ipv6.addr = "2a03:1b20:6:f011::f401";
  };
  "de-fra-wg-006" = {
    publicKey = "nAF0wrLG2+avwQfqxnXhBGPUBCvc3QCqWKH4nK5PfEU=";
    ipv4.addr = "185.209.196.76";
    ipv6.addr = "2a03:1b20:6:f011::f501";
  };
  "de-fra-wg-007" = {
    publicKey = "mTmrSuXmTnIC9l2Ur3/QgodGrVEhhIE3pRwOHZpiYys=";
    ipv4.addr = "185.209.196.77";
    ipv6.addr = "2a03:1b20:6:f011::f601";
  };
  "de-fra-wg-008" = {
    publicKey = "+DuVLLPwGNlfZFoI24PRPdaTrO4i+WPDlYaOVcavHDo=";
    ipv4.addr = "185.209.196.78";
    ipv6.addr = "2a03:1b20:6:f011::f701";
  };
  "de-fra-wg-009" = {
    publicKey = "flq7zR8W5FxouHBuZoTRHY0A0qFEMQZF5uAgV4+sHVw=";
    ipv4.addr = "185.213.155.72";
    ipv6.addr = "2a03:1b20:6:f011::f901";
  };
  "dk-cph-wg-001" = {
    publicKey = "egl+0TkpFU39F5O6r6+hIBMPQLOa8/t5CymOZV6CC3Y=";
    ipv4.addr = "45.129.56.67";
    ipv6.addr = "2a03:1b20:8:f011::f001";
  };
  "dk-cph-wg-002" = {
    publicKey = "R5LUBgM/1UjeAR4lt+L/yA30Gee6/VqVZ9eAB3ZTajs=";
    ipv4.addr = "45.129.56.68";
    ipv6.addr = "2a03:1b20:8:f011::f101";
  };
  "fi-hel-wg-001" = {
    publicKey = "veLqpZazR9j/Ol2G8TfrO32yEhc1i543MCN8rpy1FBA=";
    ipv4.addr = "185.204.1.203";
    ipv6.addr = "2a0c:f040:0:2790::a01f";
  };
  "fi-hel-wg-002" = {
    publicKey = "8BbP3GS01dGkN5ENk1Rgedxfd80friyVOABrdMgD3EY=";
    ipv4.addr = "185.204.1.211";
    ipv6.addr = "2a0c:f040:0:2790::a02f";
  };
  "fi-hel-wg-003" = {
    publicKey = "FKodo9V6BehkNphL+neI0g4/G/cjbZyYhoptSWf3Si4=";
    ipv4.addr = "185.204.1.219";
    ipv6.addr = "2a0c:f040:0:2790::a03f";
  };
  "fi-hel-wg-101" = {
    publicKey = "2S3G7Sm9DVG6+uJtlDu4N6ed5V97sTbA5dCSkUelWyk=";
    ipv4.addr = "193.138.7.137";
    ipv6.addr = "2a02:ed04:3581:1::f001";
  };
  "fi-hel-wg-102" = {
    publicKey = "xeHVhXxyyFqUEE+nsu5Tzd/t9en+++4fVFcSFngpcAU=";
    ipv4.addr = "193.138.7.157";
    ipv6.addr = "2a02:ed04:3581:2::f001";
  };
  "fi-hel-wg-103" = {
    publicKey = "Mlvu14bSD6jb7ajH/CiJ/IO8W+spB8H6VmdGkFGOcUQ=";
    ipv4.addr = "193.138.7.177";
    ipv6.addr = "2a02:ed04:3581:3::f001";
  };
  "fi-hel-wg-104" = {
    publicKey = "keRQGHUbYP2qgDTbYqOsI9byfNb0LOpTZ/KdC67cJiA=";
    ipv4.addr = "193.138.7.197";
    ipv6.addr = "2a02:ed04:3581:4::f001";
  };
  "fr-par-wg-001" = {
    publicKey = "ov323GyDOEHLT0sNRUUPYiE3BkvFDjpmi1a4fzv49hE=";
    ipv4.addr = "193.32.126.66";
    ipv6.addr = "2a03:1b20:9:f011::a01f";
  };
  "fr-par-wg-002" = {
    publicKey = "R5Ve+PJD24QjNXi2Dim7szwCiOLnv+6hg+WyTudAYmE=";
    ipv4.addr = "193.32.126.67";
    ipv6.addr = "2a03:1b20:9:f011::f101";
  };
  "fr-par-wg-003" = {
    publicKey = "w4r/o6VImF7l0/De3JpOGnpzjAFv9wcCu8Rop5eZkWc=";
    ipv4.addr = "193.32.126.68";
    ipv6.addr = "2a03:1b20:9:f011::f201";
  };
  "fr-par-wg-004" = {
    publicKey = "E/KjR7nlFouuRXh1pwGDr7iK2TAZ6c4K0LjjmA1A2Tc=";
    ipv4.addr = "193.32.126.69";
    ipv6.addr = "2a03:1b20:9:f011::f301";
  };
  "fr-par-wg-005" = {
    publicKey = "cmqtSjWUa4/0bENQDKxdr0vQqf4nFVDodarHm0Pc0hY=";
    ipv4.addr = "193.32.126.70";
    ipv6.addr = "2a03:1b20:9:f011::f401";
  };
  "fr-par-wg-006" = {
    publicKey = "x0k8A2S7Dx7VNX2Yo2qRPZW/VefIogID5bVynklBugE=";
    ipv4.addr = "193.32.126.84";
    ipv6.addr = "2a03:1b20:9:f011::f001";
  };
  "fr-par-wg-007" = {
    publicKey = "D2o4woLw59apODi8NgvVtsbEJOAF5HRxXCp3R4mzGAs=";
    ipv4.addr = "193.32.126.83";
    ipv6.addr = "2a03:1b20:9:f011::3f";
  };
  "gb-lon-wg-001" = {
    publicKey = "IJJe0TQtuQOyemL4IZn6oHEsMKSPqOuLfD5HoAWEPTY=";
    ipv4.addr = "141.98.252.130";
    ipv6.addr = "2a03:1b20:7:f011::a01f";
  };
  "gb-lon-wg-003" = {
    publicKey = "VZwE8hrpNzg6SMwn9LtEqonXzSWd5dkFk62PrNWFW3Y=";
    ipv4.addr = "185.195.232.66";
    ipv6.addr = "2a03:1b20:7:f011::a11f";
  };
  "gb-lon-wg-004" = {
    publicKey = "PLpO9ikFX1garSFaeUpo7XVSMrILrTB8D9ZwQt6Zgwk=";
    ipv4.addr = "185.195.232.67";
    ipv6.addr = "2a03:1b20:7:f011::a12f";
  };
  "gb-lon-wg-005" = {
    publicKey = "bG6WulLmMK408n719B8nQJNuTRyRA3Qjm7bsm9d6v2M=";
    ipv4.addr = "185.195.232.68";
    ipv6.addr = "2a03:1b20:7:f011::a13f";
  };
  "gb-lon-wg-006" = {
    publicKey = "INRhM0h4T1hi9j28pcC+vRv47bp7DIsNKtagaFZFSBI=";
    ipv4.addr = "185.195.232.69";
    ipv6.addr = "2a03:1b20:7:f011::a14f";
  };
  "gb-lon-wg-007" = {
    publicKey = "MVqe9e9aDwfFuvEhEn4Wd/zWV3cmiCX9fZMWetz+23A=";
    ipv4.addr = "185.195.232.70";
    ipv6.addr = "2a03:1b20:7:f011::a15f";
  };
  "gb-lon-wg-008" = {
    publicKey = "uHkxYjfx6yzPHSdyqYqSEHsgFNFV8QCSV6aghuQK3AA=";
    ipv4.addr = "141.98.252.138";
    ipv6.addr = "2a03:1b20:7:f011::f801";
  };
  "nl-ams-wg-001" = {
    publicKey = "UrQiI9ISdPPzd4ARw1NHOPKKvKvxUhjwRjaI0JpJFgM=";
    ipv4.addr = "193.32.249.66";
    ipv6.addr = "2a03:1b20:3:f011::f001";
  };
  "nl-ams-wg-002" = {
    publicKey = "DVui+5aifNFRIVDjH3v2y+dQ+uwI+HFZOd21ajbEpBo=";
    ipv4.addr = "185.65.134.82";
    ipv6.addr = "2a03:1b20:3:f011::a02f";
  };
  "nl-ams-wg-003" = {
    publicKey = "if4HpJZbN7jft5E9R9wAoTcggIu6eZhgYDvqxnwrXic=";
    ipv4.addr = "185.65.134.83";
    ipv6.addr = "2a03:1b20:3:f011::f201";
  };
  "nl-ams-wg-004" = {
    publicKey = "hnRyse6QxPPcZOoSwRsHUtK1W+APWXnIoaDTmH6JsHQ=";
    ipv4.addr = "193.32.249.69";
    ipv6.addr = "2a03:1b20:3:f011::f301";
  };
  "nl-ams-wg-005" = {
    publicKey = "33BoONMGCm2vknq2eq72eozRsHmHQY6ZHEEZ4851TkY=";
    ipv4.addr = "193.32.249.70";
    ipv6.addr = "2a03:1b20:3:f011::f401";
  };
  "nl-ams-wg-006" = {
    publicKey = "xpZ3ZDEukbqKQvdHwaqKMUhsYhcYD3uLPUh1ACsVr1s=";
    ipv4.addr = "185.65.134.86";
    ipv6.addr = "2a03:1b20:3:f011::f501";
  };
  "nl-ams-wg-007" = {
    publicKey = "Os/BwxAIWehlypQ8QjrKVEK5PhY84b413+U3YWZJYXQ=";
    ipv4.addr = "185.65.134.76";
    ipv6.addr = "2a03:1b20:3:f011::f701";
  };
  "nl-ams-wg-008" = {
    publicKey = "hf+klJbIyUoGUaFHgac9W+yriwb9uvSnafDfnmEW9Hc=";
    ipv4.addr = "193.32.249.73";
    ipv6.addr = "2a03:1b20:3:f011::f801";
  };
  "no-osl-wg-001" = {
    publicKey = "jOUZjMq2PWHDzQxu3jPXktYB7EKeFwBzGZx56cTXXQg=";
    ipv4.addr = "176.125.235.71";
    ipv6.addr = "2a02:20c8:4124::a01f";
  };
  "no-osl-wg-002" = {
    publicKey = "IhhpKphSFWpwja1P4HBctZ367G3Q53EgdeFGZro29Tc=";
    ipv4.addr = "176.125.235.72";
    ipv6.addr = "2a02:20c8:4124::a02f";
  };
  "no-osl-wg-003" = {
    publicKey = "zOBWmQ3BEOZKsYKbj4dC2hQjxCbr3eKa6wGWyEDYbC4=";
    ipv4.addr = "176.125.235.73";
    ipv6.addr = "2a02:20c8:4124::a03f";
  };
  "no-osl-wg-004" = {
    publicKey = "veeEoYS9a2T6K8WMs/MvRCdNJG580XbhnLfbFjp3B0M=";
    ipv4.addr = "176.125.235.74";
    ipv6.addr = "2a02:20c8:4124::a04f";
  };
  "no-osl-wg-005" = {
    publicKey = "ScQu/AqslSPwpXMIEyimrYZWTIdJJXLLeXrijWOF0SE=";
    ipv4.addr = "178.255.149.140";
    ipv6.addr = "2a02:20c8:4124::f401";
  };
  "no-osl-wg-006" = {
    publicKey = "LBlNBTuT7gNEZoAuxO0PTVPpaDuYA7nAeCyMpg9Agyo=";
    ipv4.addr = "178.255.149.165";
    ipv6.addr = "2a02:20c8:4124::f501";
  };
  "no-osl-wg-007" = {
    publicKey = "A0gisFM9hOZB0ezDcSIg2WwnyeprHV/dmb5JnzST0EE=";
    ipv4.addr = "91.90.44.15";
    ipv6.addr = "2a02:20c8:4124::f701";
  };
  "no-osl-wg-008" = {
    publicKey = "/4+nwTRYLjT2UK0g3+S4sjE4oaIQiS6L2b/lpO2bfwI=";
    ipv4.addr = "91.90.44.18";
    ipv6.addr = "2a02:20c8:4124::f801";
  };
  "no-svg-wg-001" = {
    publicKey = "kduYoE/b1mA2Pjszx1CzE4Lktsdc2zsUU8Relul2m2U=";
    ipv4.addr = "194.127.199.2";
    ipv6.addr = "2a02:20c8:4120::a01f";
  };
  "no-svg-wg-002" = {
    publicKey = "U9fbFesIIr2HotWdkfMpKyOEPk+RYtE2oYn3KoLmkj4=";
    ipv4.addr = "194.127.199.31";
    ipv6.addr = "2a02:20c8:4120::a02f";
  };
  "no-svg-wg-003" = {
    publicKey = "btc4mh3n9jVCW6yikw3cOPct0x3B5cDK+kKnvgCV0S0=";
    ipv4.addr = "194.127.199.62";
    ipv6.addr = "2a02:20c8:4120::a03f";
  };
  "no-svg-wg-004" = {
    publicKey = "Fu98PLCZw/FTcQqyTy0vzaepkfxuSLAah7wnafGVO1g=";
    ipv4.addr = "194.127.199.93";
    ipv6.addr = "2a02:20c8:4120::a04f";
  };
  "se-got-wg-001" = {
    publicKey = "5JMPeO7gXIbR5CnUa/NPNK4L5GqUnreF0/Bozai4pl4=";
    ipv4.addr = "185.213.154.66";
    ipv6.addr = "2a03:1b20:5:f011:31::a03f";
  };
  "se-got-wg-002" = {
    publicKey = "AtvE5KdPeQtOcE2QyXaPt9eQoBV3GBxzimQ2FIuGQ2U=";
    ipv4.addr = "185.213.154.67";
    ipv6.addr = "2a03:1b20:5:f011::a05f";
  };
  "se-got-wg-003" = {
    publicKey = "BLNHNoGO88LjV/wDBa7CUUwUzPq/fO2UwcGLy56hKy4=";
    ipv4.addr = "185.213.154.68";
    ipv6.addr = "2a03:1b20:5:f011::a09f";
  };
  "se-got-wg-004" = {
    publicKey = "veGD6/aEY6sMfN3Ls7YWPmNgu3AheO7nQqsFT47YSws=";
    ipv4.addr = "185.213.154.69";
    ipv6.addr = "2a03:1b20:5:f011::a10f";
  };
  "se-got-wg-005" = {
    publicKey = "x4h55uXoIIKUqKjjm6PzNiZlzLjxjuAIKzvgU9UjOGw=";
    ipv4.addr = "185.209.199.2";
    ipv6.addr = "2a03:1b20:5:f011:5::f001";
  };
  "se-got-wg-006" = {
    publicKey = "dcSpHioI+TY37dbZcviFA/sxSUqmpECXRZIapwR8pVg=";
    ipv4.addr = "185.209.199.7";
    ipv6.addr = "2a03:1b20:5:f011:6::f001";
  };
  "se-got-wg-007" = {
    publicKey = "ywfkKYdoVAnjsSYW145ACtrw3DV8xTzFS1hlIO7QRD4=";
    ipv4.addr = "185.209.199.12";
    ipv6.addr = "2a03:1b20:5:f011:7::f001";
  };
  "se-got-wg-008" = {
    publicKey = "Vh3Y2LsBG1yN4kDeebOr3J6dFooGJIBTftzVqlWhiD4=";
    ipv4.addr = "185.209.199.17";
    ipv6.addr = "2a03:1b20:5:f011:8::f001";
  };
  "se-got-wg-101" = {
    publicKey = "B8UVAeNkAW4NiGHd1lpl933Drh4y7pMqpXJpH0SrGjQ=";
    ipv4.addr = "185.213.154.70";
    ipv6.addr = "2a03:1b20:5:f011::aaaf";
  };
  "se-mma-wg-001" = {
    publicKey = "Qn1QaXYTJJSmJSMw18CGdnFiVM0/Gj/15OdkxbXCSG0=";
    ipv4.addr = "193.138.218.220";
    ipv6.addr = "2a03:1b20:1:f410::a01f";
  };
  "se-mma-wg-002" = {
    publicKey = "5y66WShsFXqM5K7/4CPEGCWfk7PQyNhVBT2ILjbGm2I=";
    ipv4.addr = "193.138.218.80";
    ipv6.addr = "2a03:1b20:1:f410::a15f";
  };
  "se-mma-wg-003" = {
    publicKey = "fZFAcd8vqWOBpRqlXifsjzGf16gMTg2GuwKyZtkG6UU=";
    ipv4.addr = "193.138.218.83";
    ipv6.addr = "2a03:1b20:1:f410::a18f";
  };
  "se-mma-wg-004" = {
    publicKey = "m4jnogFbACz7LByjo++8z5+1WV0BuR1T7E1OWA+n8h0=";
    ipv4.addr = "193.138.218.130";
    ipv6.addr = "2a03:1b20:1:f410:40::a04f";
  };
  "se-mma-wg-005" = {
    publicKey = "qnJrQEf2JiDHMnMWFFxWz8I9NREockylVgYVE95s72s=";
    ipv4.addr = "193.138.218.82";
    ipv6.addr = "2a03:1b20:1:f410::a17f";
  };
  "se-mma-wg-011" = {
    publicKey = "vclzw8ytARhkEqw4cLUJPC3REvMZqWsO+7TYD/U2UVk=";
    ipv4.addr = "141.98.255.94";
    ipv6.addr = "2a03:1b20:1:f410::f101";
  };
  "se-mma-wg-012" = {
    publicKey = "aPcHJj3I1oISU8cwLz2Uyq4ctUOXdTpuS96aW89snUs=";
    ipv4.addr = "141.98.255.97";
    ipv6.addr = "2a03:1b20:1:f410::f201";
  };
  "se-mma-wg-101" = {
    publicKey = "7ncbaCb+9za3jnXlR95I6dJBkwL1ABB5i4ndFUesYxE=";
    ipv4.addr = "45.83.220.68";
    ipv6.addr = "2a03:1b20:1:e011::a21f";
  };
  "se-mma-wg-102" = {
    publicKey = "cwglRdgLQ4gMG36TIYlc5OIemLNrYs4UM1KTc8mnzxk=";
    ipv4.addr = "45.83.220.69";
    ipv6.addr = "2a03:1b20:1:e011::a22f";
  };
  "se-mma-wg-103" = {
    publicKey = "XscA5gebj51nmhAr6o+aUCnMHWGjbS1Gvvd0tuLRiFE=";
    ipv4.addr = "45.83.220.70";
    ipv6.addr = "2a03:1b20:1:e011::a23f";
  };
  "se-mma-wg-111" = {
    publicKey = "vi0PPk0ZCDvDMCSQD0mctmPFFH7NiawLxJquyPIGwAY=";
    ipv4.addr = "45.129.59.19";
    ipv6.addr = "2a03:1b20:1:e011::f701";
  };
  "se-mma-wg-112" = {
    publicKey = "bysuFAwy+jwl5IePhY06/j7ByWDsAtU5pKPo44k4qEY=";
    ipv4.addr = "45.129.59.129";
    ipv6.addr = "2a03:1b20:1:e011::f601";
  };
  "se-sto-wg-001" = {
    publicKey = "MkP/Jytkg51/Y/EostONjIN6YaFRpsAYiNKMX27/CAY=";
    ipv4.addr = "185.195.233.76";
    ipv6.addr = "2a03:1b20:4:f011::999f";
  };
  "se-sto-wg-002" = {
    publicKey = "q2ZZPfumPaRVl4DJfzNdQF/GHfe6BYAzQ2GZZHb6rmI=";
    ipv4.addr = "185.65.135.67";
    ipv6.addr = "2a03:1b20:4:f011::a02f";
  };
  "se-sto-wg-003" = {
    publicKey = "qZbwfoY4LHhDPzUROFbG+LqOjB0+Odwjg/Nv3kGolWc=";
    ipv4.addr = "185.65.135.68";
    ipv6.addr = "2a03:1b20:4:f011::f201";
  };
  "se-sto-wg-007" = {
    publicKey = "YD4k8xaiw2kcRhfLRf2UiRNcDmvvu5NV0xT4d5xOFzU=";
    ipv4.addr = "185.65.135.70";
    ipv6.addr = "2a03:1b20:4:f011::b07f";
  };
  "se-sto-wg-008" = {
    publicKey = "4nOXEaCDYBV//nsVXk7MrnHpxLV9MbGjt+IGQY//p3k=";
    ipv4.addr = "185.65.135.71";
    ipv6.addr = "2a03:1b20:4:f011::f701";
  };
  "se-sto-wg-009" = {
    publicKey = "t1XlQD7rER0JUPrmh3R5IpxjUP9YOqodJAwfRorNxl4=";
    ipv4.addr = "185.195.233.69";
    ipv6.addr = "2a03:1b20:4:f011::a09f";
  };
  "se-sto-wg-010" = {
    publicKey = "pWhNidLbYca9j66c7iw/3kgtU+UyFRIgc75xy8riqzg=";
    ipv4.addr = "185.195.233.70";
    ipv6.addr = "2a03:1b20:4:f011::a10f";
  };
  "se-sto-wg-011" = {
    publicKey = "GqKpm8VwKJQLQEQ0PXbkRueY9hDqiMibr+EpW3n9syk=";
    ipv4.addr = "185.195.233.71";
    ipv6.addr = "2a03:1b20:4:f011::a11f";
  };
  "se-sto-wg-012" = {
    publicKey = "1493vtFUbIfSpQKRBki/1d0YgWIQwMV4AQAvGxjCNVM=";
    ipv4.addr = "185.195.233.66";
    ipv6.addr = "2a03:1b20:4:f011::fb01";
  };
  "se-sto-wg-013" = {
    publicKey = "u3pZZjXm0NHCNqPIhKlZ7Vy6CQm5G9YpfgvaywurTho=";
    ipv4.addr = "185.195.233.67";
    ipv6.addr = "2a03:1b20:4:f011::fe01";
  };
}
