#!/usr/bin/env sh

trustedKey=me@azey.net
trustedKeyFP=2CCB340343FE8A2B91CE7F75F94F4A71C5C21E8F

if [ -z "$@" ]
then
	sleep $(shuf -i 0-60 -n 1)m # random delay 0-60m
fi
#
# import pubkeys
gpg --auto-key-locate cert,dane --locate-keys "$trustedKey"
gpg --import "$(dirname "$0")/renovate.pgp"

# make sure repo is clean & fetch
cd /etc/nixos

if ! [ "$(git status --porcelain=v1 -b | sed 's/ \[behind [0-9]*\]//')" = "## main...origin/main" ]
then
	echo "dirty repo, skipping auto-update"
	echo
	git status
	exit 1
fi
git fetch -q

# check commits against signature
# userid doesn't seem spoofable in a way that'd make verify-commit --raw match the pattern, since newlines in it get output as \n
echo -n "processing origin/HEAD ($(git rev-parse origin/HEAD))..."
i=0
while ! git verify-commit --raw origin/HEAD~$i 2>&1 | grep -q "^\\[GNUPG:\\] VALIDSIG $trustedKeyFP "
do
	# if no match, check if it matches renovate's signature & commit pattern
	# I really can't be bothered trying to parse .renovaterc and applying it to git diff, this should be more than good enough
	{ git verify-commit --raw origin/HEAD~$i 2>&1 | grep -q '^\[GNUPG:\] VALIDSIG 8597C121F9054BFE10F91B789D5772AC74E63568 '; } || {
		echo -e "FAIL\nSECURITY ERROR: commit not signed by any trusted key"
		exit 1
	}

	{ ! git diff origin/HEAD~$((i+1)) origin/HEAD~$i --name-status | grep -vqE '^M' | grep -vqP '^R\d\d\d\t(config/rke2/helm-images/[a-zA-z.-]+_)[a-zA-z.-]+\.nix\t\1[a-zA-z.-]+\.nix$'; } || {
		echo -e "FAIL\nSECURITY ERROR: signed renovate-bot commit moved/deleted/added files outside of config/rke2/helm-images"
		echo
		git diff origin/HEAD~$((i+1)) origin/HEAD~$i --name-status
		exit 1
	}

	# remove diff headers based on colors
	#   technically it's possible to add a color ANSI code that then gets removed by the sed, but
	#   at worst that'd cause the later nixos-rebuild to fail on eval & send a notif anyways
	diff="$(git diff HEAD -U0 --color | grep -Pv '^\e\[1m' | grep -Pv '^\e\[36m' | sed 's/\x1b\[[0-9;]*m//g')"

	# remove OK lines from $diff & check if it's empty
	for name in version image imageDigest finalImageTag revision hash
	do
		diff="$(echo "$diff" | grep -vE "^[+|-]\s+$name\s+=\s+\"\S+\";")"
	done

	if [ "$diff" != "" ]
	then
		echo -e "FAIL\nSECURITY ERROR: signed renovate-bot commit changed something it shouldn't be allowed to"
		echo
		echo "$diff"
		exit 1
	fi

	# commit seems safe enough, continue
	echo "OK [renovate-bot]"
	echo -n "processing origin/HEAD~$((++i)) ($(git rev-parse origin/HEAD~$i))..."
done
echo "OK [$trustedKey]"
echo "COMMIT CHAIN VERIFIED"

# commits are good, pull & apply
if [ -z "$@" ]
then
	git pull || exit 1
	nixos-rebuild switch || exit 1
	systemctl restart rke2-server
fi
